# Change these first
owner: BradGunnerSGT # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
robotsText: "User-agent: * \n Disallow: /"

sites:
  - name: Personal site
    url: https://markmccoy.us
  - name: UTSA Main site
    url: https://utsa.edu
  - name: UTSA my.utsa.edu
    url: https://my.utsa.edu
  - name: ADFS JPL1 (White)
    url: https://adfs-jpl2.it.utsa.edu
    __dangerous__disable_verify_host: true
  - name: ADFS JPL2 (Grey)
    url: https://adfs-jpl2.it.utsa.edu
    __dangerous__disable_verify_host: true
  - name: ADFS AET1 (Pink)
    url: https://adfs-jpl2.it.utsa.edu
    __dangerous__disable_verify_host: true
  - name: ADFS AET2 (Jade)
    url: https://adfs-jpl2.it.utsa.edu
    __dangerous__disable_verify_host: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data. Based on the [Upptime monitoring tool](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
